### ISSUE TITLE
Patching Error On Mac

### ISSUE THREAD

**Issue by moistbutter** [Lauriethefish/QuestPatcher#20]
I have SideQuest INstalled and My Quest 2 is Plugged in. This is the issue that pops up when I attempt to "Patch My App!"
```
Signing APK (this might take a while) . . .
Signing the APK failed with zipalign enabled. Falling back to non-zipalign . . .
Patching failed!: QuestPatcher.Core.SigningException: Signed APK at /var/folders/2r/2fwdq09s3331t8_5c81s151w0000gn/T/QuestPatcher/patching/patched-debugSigned.apk was missing, signing must have failed
   at QuestPatcher.Core.ApkTools.SignApk(String apkPath, Boolean useZipAlign) in /Users/runner/work/QuestPatcher/QuestPatcher/QuestPatcher.Core/ApkTools.cs:line 119
   at QuestPatcher.Core.Patching.PatchingManager.PatchApp() in /Users/runner/work/QuestPatcher/QuestPatcher/QuestPatcher.Core/Patching/PatchingManager.cs:line 393
   at QuestPatcher.ViewModels.PatchingViewModel.StartPatching() in /Users/runner/work/QuestPatcher/QuestPatcher/QuestPatcher/ViewModels/PatchingViewModel.cs:line 59
```

**Comment by Lauriethefish** [comment]
Please send a full log by going to the tools tab, clicking `Open Logs Folder` and sending the log file here.
I cannot help without more information.

**Comment by moistbutter** [comment]
[log.log](https://github.com/Lauriethefish/QuestPatcher/files/6835252/log.log)
Hope this works

**Comment by moistbutter** [comment]
Sorry I commented But I don't think I replied So I don't know if it alerted you
[log.log](https://github.com/Lauriethefish/QuestPatcher/files/6835555/log.log)

**Comment by Lauriethefish** [comment]
Updating Java should fix this issue

**Comment by moistbutter** [comment]
My Mac says It has the recommended version of Java, Java 8, update 291.

**Comment by Lauriethefish** [comment]
`Exception in thread "main" java.lang.UnsupportedClassVersionError: at/favre/tools/apksigner/SignTool : Unsupported major.minor version 52.0` - the signer isn't convinced you have Java 8. I'd uninstall and reinstall just to be sure.

**Comment by moistbutter** [comment]
I reinstalled Java and questpatcher, wasnt quite sure which one you meant, I followed the website instructions on javas website. the error still apears. 
[log.log](https://github.com/Lauriethefish/QuestPatcher/files/6841505/log.log)

**Comment by Lauriethefish** [comment]
Hmm, I am not sure at this point. In the log, the java version installed cannot load Java 8 code, which is needed for QuestPatcher to sign the APK. Not much I can do really if an older java version is installed, even after a java reinstall and a reboot.

**Comment by moistbutter** [comment]
I have a windows laptop from 2015, i don't use it because the screens broken but i can plug it into a monitor, do i have to install sidequest if I do it from there?

**Comment by moistbutter** [comment]
Sorry Im kinda Picking at scraps here I really wanted these mods.

**Comment by Lauriethefish** [comment]
The windows laptop might work, go ahead and try it.

**Comment by Lauriethefish** [comment]
Closing since this isn't a QP issue.
